name: Update Products XML

on:
  schedule:
    - cron: "0 12 * * *" # Запуск каждый день в 19:00 по новосибирскому времени (UTC+7)
  workflow_dispatch: # Позволяет запускать workflow вручную

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Обновлено до последней версии

      - name: Set up Python
        uses: actions/setup-python@v5 # Обновлено до последней версии
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update tyres
        run: python zapaska_tyres.py
        continue-on-error: true
        
      - name: Run update disks
        run: python zapaska_disks.py
        continue-on-error: true

      - name: Check for changes
        id: changes
        if: always()
        run: |
          git add tyres.xml disks.xml
          if git diff-index --quiet HEAD; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi
        
      - name: Commit and push changes
        if: always() && steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -m 'Daily update of products XML'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
